<?php
/**
 * Created by PhpStorm.
 * User: svatoslavzilicev
 * Date: 19.03.14
 * Time: 17:24
 */
?>
<div class="add-new">
    <form id="addsiteform" action="<?php echo BASE_URL.'sites/add' ?>" method="post">
        <div class="line">
            <label for="name">Name</label>
            <input id="name" name="name" type="text" value="<?php echo str_replace('/','',str_replace(Core::getRootCatalogPath(),'',Core::getParam('path'))) ?>"/>
            <div class="clear"></div>
        </div>
        <div class="line">
            <label for="url">URL</label>
            <input id="url" name="url" type="text" value="http://"/>
            <div class="clear"></div>
        </div>
        <div class="line">
            <label for="path">Path</label>
            <input id="path" name="path" type="text" value="<?php echo Core::getParam('path') ?>"/>
            <div class="clear"></div>
        </div>
        <div class="line">
            <label for="description">Description</label>
            <textarea id="description" name="description" ></textarea>
            <div class="clear"></div>
        </div>
        <div class="add-new-buttonset">
            <button type="submit">Add</button>
            <div class="clear"></div>
        </div>
    </form>
</div>